# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  my-app:
    build:
      context: .
    ports:
      - 8081:8081
    develop:
      watch:
        - action: sync
          path:
             ./frontend/SafeBitesReactApp/app/login.tsx
          target: /frontend/SafeBitesReactApp/app/login.tsx
          ignore:
            - node_modules
    depends_on:
      - server

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build:
      context: ./backend/server
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/mydb?authSource=admin
      NODE_ENV: production
    depends_on:
      - mongo

volumes:
  mongo_data: